name: CI - Build and Push Image

permissions:
  contents: read
  security-events: write
  actions: read

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      PROJECT_NAME: strapi

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          VERSION=8.28.0
          curl -L https://github.com/gitleaks/gitleaks/releases/download/v${VERSION}/gitleaks_${VERSION}_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz
          sudo mv gitleaks /usr/local/bin/
          gitleaks version
          
      - name: Run Gitleaks
        run: |
          gitleaks git --verbose

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: strapi-app/package-lock.json

      - name: Install Dependencies
        working-directory: ./strapi-app
        run: npm install

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Ensure ECR Repository Exists
        run: |
          aws ecr describe-repositories --repository-names ${PROJECT_NAME}-repo-jayani || \
          aws ecr create-repository --repository-name ${PROJECT_NAME}-repo-jayani

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        id: build-image
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          REGISTRY="${{ steps.login-ecr.outputs.registry }}"
          REPO_NAME="${PROJECT_NAME}-repo-jayani"

          IMAGE_URI="$REGISTRY/$REPO_NAME:$IMAGE_TAG"

          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

          docker build -t "$IMAGE_URI" ./strapi-app

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{ env.IMAGE_URI }}
          format: table
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1

      - name: Push Docker Image
        run: |
          docker push "${{ env.IMAGE_URI }}"
